#pragma config(Sensor, S1,     HTPB,           sensorI2CCustom9V)
#pragma config(Sensor, S2,     ,               sensorTouch)
#pragma config(Sensor, S3,     ,               sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Arduino to Hitechnic Protoboard
// Wiring:
//  Arduino   to     Hitechnic
//    D4                A0
//    D5                A1
//    D6                A2
//    D7                A3
//    D8                A4
//    D9                B0
//    D10               B1
//    A0                B2
//    A1                B3
//    D2 (interupt)     B4 (output)
//    D3 (inretput)     B5 (output)
//////////////////////////////////

#include "drivers/hitechnic-protoboard.h"

int mapNineBitToDegrees(int nineBitNum)
{
	float Degrees = 0;
	float NineBitNum = 0;
	float slope = 360.0/512.0;

	NineBitNum = (float)(nineBitNum);
	Degrees=slope*NineBitNum;
	Degrees=Degrees - 180.0;
	return (int)(Degrees);
}

task main() {
  int _chVal = 0;  // analog input
  byte inputs = 0;  // all digital inputs
  int value = 0;
  int touchValue = 0;
  int touchValue2 = 0;

  nxtDisplayCenteredTextLine(0, "HiTechnic");
  nxtDisplayCenteredBigTextLine(1, "Proto");
  nxtDisplayCenteredTextLine(3, "Test 1");
  nxtDisplayCenteredTextLine(5, "Connect HTPB");
  nxtDisplayCenteredTextLine(6, "to S1");

  wait1Msec(2000);
  // Setup all the digital IO ports as outputs (0x30) 110000 pins B4/B5 = outputs, others are inputs.
  if (!HTPBsetupIO(HTPB, 0x30)) {
    nxtDisplayTextLine(4, "ERROR!!");
    wait1Msec(2000);
    StopAllTasks();
  }

  while(true) {
    value = 0;
  	eraseDisplay();
    // get the value for ADC channel 0, we want a 10 bit answer
		int j = 0;
		for(int i=0; i<5; i++)
		{

				_chVal = HTPBreadADC(HTPB, j, 10);
				switch(j) {
					case 0:  nxtDisplayTextLine(0, "A0: %d", _chVal);
					if(_chVal>512) value+=(1<<8);
					break;
					case 1:  nxtDisplayTextLine(1, "A1: %d", _chVal);
					if(_chVal>512) value+=(1<<7);
					break;
					case 2:  nxtDisplayTextLine(2, "A2: %d", _chVal);
					if(_chVal>512) value+=(1<<6);
					break;
					case 3:  nxtDisplayTextLine(3, "A3: %d", _chVal);
					if(_chVal>512) value+=(1<<5);
					break;
					case 4:  nxtDisplayTextLine(4, "A4: %d", _chVal);
					if(_chVal>512) value+=(1<<4);
					break; }

    	  j++;

  }
  inputs = HTPBreadIO(HTPB, 0x3F);
  nxtDisplayTextLine(5, "D: 0x%x", inputs);
  value+=(inputs&0x01)<<3;
  value+=(inputs&0x02)<<1;
  value+=(inputs&0x04)>>1;
  value+=(inputs&0x08)>>3;
  nxtDisplayBigTextLine(6, "%d", mapNineBitToDegrees(value));
  touchValue = SensorValue[S2];
  touchValue2 = SensorValue[S3];
  if(touchValue == 1 && touchValue2 == 1) { HTPBwriteIO(HTPB, 0x30); }  // turn on B4 and B5
  else if(touchValue == 1) { HTPBwriteIO(HTPB, 0x10); }  // turn on B4
  else if(touchValue2 == 1)  { HTPBwriteIO(HTPB, 0x20); }  // turn on B5
  else { HTPBwriteIO(HTPB, 0x00); } // turn both B4 and B5 off
  wait1Msec(50);
}
}
/*
 * $Id: hitechnic-protoboard-test1.c 133 2013-03-10 15:15:38Z xander $
 */
