#pragma config(Sensor, S1,     ,               sensorI2CCustom)
#pragma config(Sensor, S2,     IR,             sensorI2CCustom)
#pragma config(Sensor, S3,     Color,          sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../libraries/Servos.h"
#include "../libraries/Motors.h"
#include "LineOfBestFit.c"
#include "hitechnic-colour-v1.h"

int A, B, C, D, E = 0;
string State = "Searching";
int ColorNumber;
int IRSlope;

void MoveTobias(int RightPower, int LeftPower)
{
	Motors_SetSpeed(S1, 1, 1, RightPower);
	Motors_SetSpeed(S1, 1, 2, RightPower);
	Motors_SetSpeed(S1, 2, 1, -LeftPower);
	Motors_SetSpeed(S1, 2, 2, -LeftPower);

}
task main()
{
	//sets up initial encoder
	int Encoder = I2C_GetEncoderPosition(S1, 2, 1);
	int InitialEncoder = I2C_GetEncoderPosition(S1, 2, 1);

	while(true)
	{
		writeDebugStream("%i, ", ColorNumber);
		writeDebugStreamLine(State);

		//updates variables which are accesesd in State Machine
		Encoder = I2C_GetEncoderPosition(S1, 2, 1);
		ColorNumber = HTCSreadColor(Color);
		IRSlope = LineOfBestFit_Slope(10);

		if(State == "Searching")
		{
			MoveTobias(15, 15);

			if(ColorNumber == 2 || ColorNumber == 8)
			{
				State = "Following Line";
			}

			if(IRSlope < 0)
			{
				State = "Found";
			}
		}

		if(State == "Following Line")
		{
			//on line
			if(ColorNumber == 2 || ColorNumber == 8)
			{
				MoveTobias(35, 40);
			}

			//off line
			else
			{
				MoveTobias(40, 35);
			}

			if(IRSlope < 0)
			{
				State = "Found";
			}
		}
		if(State == "Found")
		{
			if (Encoder - InitialEncoder < (-2 * 1440))
			{
				State = "Moving Short";
			}
			else
			{
				State = "Moving Long";
			}
		}

		if(State == "Moving Short")
		{
			writeDebugStreamLine("Short");
			MoveTobias(0, 0);
			sleep(5000);
			State = "Moving Past Line";
		}

		if(State == "Moving Long")
		{
			writeDebugStreamLine("Long");

			MoveTobias(20, 20);

			sleep(350);

			MoveTobias(0, 0);

			sleep(5000);

			State = "Moving Past Line";
		}

		if(State == "Moving Past Line")
		{
			if(Encoder - InitialEncoder < (-4 * 1440))
			{
				State = "Ramp";
			}

			//on line
			if(ColorNumber == 2 || ColorNumber == 8)
			{
				MoveTobias(35, 40);
			}

			//off line
			else
			{
				MoveTobias(40, 35);
			}
		}

		if(State == "Ramp")
		{
			MoveTobias(20, 60);
			sleep(2600);
			MoveTobias(80, 80);
			sleep(1000);
			MoveTobias(0, 0);
			while(true)
			{
			}
		}
	}
}
