#pragma config(Sensor, S1,     ,               sensorI2CCustom)
#pragma config(Sensor, S2,     IR,             sensorI2CCustom)
#pragma config(Sensor, S3,     Color,          sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../libraries/Servos.h"
#include "../libraries/Arm.c"
#include "../libraries/Motors.h"
#include "LineOfBestFit.c"
#include "hitechnic-colour-v1.h"

int A, B, C, D, E = 0;
string State = "Searching";
int ColorNumber;
int IRSlope;
int Encoder;
int InitialEncoder;

void Move(int RightPower, int LeftPower)
{
	Motors_SetSpeed(S1, 2, 1, RightPower);
	Motors_SetSpeed(S1, 2, 2, -LeftPower);
}

void FollowLine()
{
	//on line
	if(ColorNumber == 2 || ColorNumber == 8)
	{
		Move(27, 30);
	}

	//off line
	else
	{
		Move(30, 27);
	}
}

task main()
{
	//sets up initial encoder
	InitialEncoder = I2C_GetEncoderPosition(S1, 2, 2);
	while(true)
	{

		writeDebugStreamLine("%i", (ColorNumber == 2 || ColorNumber == 8));

		//updates variables which are accesesd in State Machine
		Encoder = I2C_GetEncoderPosition(S1, 2, 2);
		ColorNumber = HTCSreadColor(Color);
		IRSlope = LineOfBestFit_Slope(10);
		Arm_Update();

		if(State == "Searching")
		{
			Arm_SetSpeed(-100);
			Move(15, 15);

			if(ColorNumber == 2 || ColorNumber == 8)
			{
				State = "Following Line";
			}

			if(IRSlope < 0)
			{
				State = "Found";
			}
		}

		if(State == "Following Line")
		{
			Arm_SetSpeed(-100);
			if(IRSlope < 0)
			{
				State = "Found";
			}

			FollowLine();
		}

		if(State == "Found")
		{
			if (Encoder - InitialEncoder < (-2 * 1440))
			{
				State = "Moving Short";
			}
			else
			{
				State = "Moving Long";
			}
		}

		if(State == "Moving Short")
		{
			writeDebugStreamLine("Short");
			Move(50, 50);
			sleep(200);
			Move(0, 0);
			//sleep(5000);
			State = "Turn";

			Arm_SetSpeed(0);
			Arm_Update();
		}

		if(State == "Moving Long")
		{
			writeDebugStreamLine("Long");

			Move(50, 50);

			sleep(450);

			Move(0, 0);

			//sleep(5000);

			State = "Turn";

			Arm_SetSpeed(0);
			Arm_Update();
		}

		if (State == "Turn")
		{
			Motors_MoveRotations(S1, 2, 1, -1.4, 20);
			//Motors_MoveRotations(S1, 2, 2, -.7, 20);
			State = "Drop Block"
		}

		if(State == "Drop Block")
		{
			sleep(2000);
			Servos_SetPosition(S1, 3, 1, 0);
			while(true)
			{
			}
		}

		if(State == "Moving Past Line")
		{
			if(Encoder - InitialEncoder < (-3.6 * 1440))
			{
				State = "Ramp";
			}

			FollowLine();
		}

		if(State == "Ramp")
		{
			Move(0, 0);
			//Move(15, 60);
			//sleep(2100);
			//Move(80, 80);
			//sleep(1300);
			//Move(0, 0);
			while(true)
			{
			}
		}
	}
}
