#pragma config(Sensor, S1,     ,               sensorI2CCustom)
#pragma config(Sensor, S2,     ,               sensorI2CCustom)
#pragma config(Sensor, S3,     ,               sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "libraries/Motors.h"

const int speed = -10;

/*
	Motor 1 Daisychain 1 on S1 is left front
	Motor 2 Daisychain 1 on S1 is left back
	Motor 1 Daisychain 2 on S1 is right front
	Motor 2 Daisychain 2 on S1 is right back
*/

task main()
{

	Motors_SetSpeed(S1, 1, 1, speed);
	Motors_SetSpeed(S1, 1, 2, speed);
	Motors_SetSpeed(S1, 2, 1, -speed);
	Motors_SetSpeed(S1, 2, 2, -speed);

	/*motor[motorD] = speed;
	motor[motorE] = speed;
	motor[motorF] = -speed;
	motor[motorG] = -speed;*/

	/*for (int i = 0; i < 10000; i++) {
		eraseDisplay();
		//writeDebugStreamLine("%i", nMotorEncoder[motorE]);
		//nxtDisplayString(1, "%i", nPgmTime);
		Sleep(1);
}*/

	Sleep(5000);

}
