#pragma config(Sensor, S1,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "libraries/prober.h"

task main()
{

	nxtDisplayString(0, "%i", getSensorType(S1));
	Sleep(1000);

}
