#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorB,          leftDrive,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightDrive,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int rightPower = 0;
int leftPower = 0;

void drive()
{
	if(joystick.joy1_y2 > 0) //right side
	{
		if(abs(joystick.joy1_y2) > 10)
		{
			rightPower = (joystick.joy1_y2 - 10) * 100/118;
		}
		else
		{
			rightPower = 0 ;
		}
	}

//left side

	if(joystick.joy1_y1 > 0)
	{
		if(joystick.joy1_y1 > 10)
		{
			leftPower = (joystick.joy1_y1 - 10) * 118/100;
		}
		else
		{
			leftPower = 0;
		}
	}
}

task main()
{
	getJoystickSettings(joystick);
	while(true)
	{
		getJoystickSettings(joystick);
		drive();
		motor[motorD] = rightPower;
		motor[motorE] = leftPower;
	}


}
