#pragma config(Sensor, S1,     ,               sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "libraries/Arm.c"


task main()
{
while(true) {
	Arm_SetSpeed(-60);
	Arm_Update();

}
}
