#pragma config(Sensor, S2,     IR,             sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "libraries/IR.c";

task main()
{
	while(!IR_InFront())
	{
	}
	PlayImmediateTone(100, 100);
	Sleep(1000);
}
