#pragma config(Sensor, S1,     ,               sensorI2CCustom)
#pragma config(Sensor, S2,     Gyro,          sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../libraries/Gyro.c"
#include "../libraries/Motors.h"

float FinalX = 5;
float FinalY = 0;
float Heading = 0;
float ChangePerSecond = 0;
float TotalDrift = 0;

void Move(int RightPower, int LeftPower)
{
	Motors_SetSpeed(S1, 2, 1, RightPower);
	Motors_SetSpeed(S1, 2, 2, -LeftPower);
}

task main()
{
	Gyro_Start();

	//calibration phase
	sleep(5000);
	FinalY = Gyro_Heading();

	//finds drift slope
	ChangePerSecond = abs(FinalY) / FinalX;



	//TotalDrift -= ChangePerSecond * 5;

	while(true)
	{
		TotalDrift -= ChangePerSecond * Time1[T3] / 1000;
		Time1[T3] = 0;
		Heading = Gyro_Heading() + TotalDrift;
		writeDebugStreamLine("Total Drift: %f, ", TotalDrift);
		writeDebugStreamLine("Gyro Raw: %f, ", Gyro_Heading());
		writeDebugStreamLine("Calculated Heading: %f, ", Heading);
		writeDebugStream("PowerOne: %f, ", 20 - Heading);
		writeDebugStreamLine("PowerTwo: %f, ", 20 + Heading);
		Move(20 + Heading, 20 - Heading);
	}
}
