#pragma config(Sensor, S1,     Gyro,           sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-gyro.h"
#include "../libraries/Gyro.c"
#include "../libraries/I2C.h"

//target rate is degrees per second, seconds is not in milliseconds
int Calibrate(int TargetRate, int Seconds)
{
	//initialize
	int MotorSpeed = 0;
	time1[T3] = 0;
	int StartEncoder = I2C_GetEncoderPosition(S2, 1, 1);

	while(time1[T3] < Seconds * 1000)
	{
		//sleep and content
		sleep(50);

		eraseDisplay();
		nxtDisplayString(1, "%i", MotorSpeed);

		//calculates rate and adds or subtracts motor speed
		float Rate = abs(I2C_GetEncoderPosition(S2, 1, 1) - StartEncoder) / 1440.0 * 360.0 / (time1[T2] / 1000.0);
		time1[T2] = 0;

		MotorSpeed += 0.1 * (TargetRate - Rate);

		//sets the motor speed
		I2C_SetMotorSpeed(S2, 1, 1, MotorSpeed);
	}
}

task main()
{
	Calibrate(360, 10);

	//starts the calibration
	HTGYROsetCal(S1, HTGYROstartCal(S1));

	float Heading = 0;
	float RotationSpeed = 0;
	time1[T1] = 0;

	while(true)
	{
		//sleep and all logic here
		sleep(5);
		eraseDisplay();
		nxtDisplayString(1, "%i", Heading);

		//compute heading
		RotationSpeed = HTGYROreadRot(Gyro);
		Heading += RotationSpeed * (time1[T1] / 1000.0);
		time1[T1] = 0;
	}
}
