#pragma config(Sensor, S1,     ,               sensorI2CCustom)
#pragma config(Sensor, S2,     IR,             sensorI2CCustom)
#pragma config(Sensor, S3,     Color,          sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../libraries/Servos.h"
#include "../libraries/Motors.h"
#include "LineOfBestFit.c"
#include "hitechnic-colour-v1.h"

int A, B, C, D, E = 0;
string State = "Searching";
int ColorNumber;
int IRSlope;
int Encoder;
int InitialEncoder;

void Move(int RightPower, int LeftPower)
{
	Motors_SetSpeed(S1, 2, 1, RightPower);
	Motors_SetSpeed(S1, 2, 2, -LeftPower);
}

void FollowLine()
{
	//on line
	if(ColorNumber == 2 || ColorNumber == 8)
	{
		Move(25, 30);
	}

	//off line
	else
	{
		Move(30, 25);
	}
}

task main()
{
	//sets up initial encoder
	InitialEncoder = I2C_GetEncoderPosition(S1, 2, 2);
	while(true)
	{

		writeDebugStreamLine("%i", (ColorNumber == 2 || ColorNumber == 8));

		//updates variables which are accesesd in State Machine
		Encoder = I2C_GetEncoderPosition(S1, 2, 2);
		ColorNumber = HTCSreadColor(Color);
		IRSlope = LineOfBestFit_Slope(10);

		if(State == "Searching")
		{
			Move(15, 15);

			if(ColorNumber == 2 || ColorNumber == 8)
			{
				State = "Following Line";
			}

			if(IRSlope < 0)
			{
				State = "Found";
			}
		}

		if(State == "Following Line")
		{
			if(IRSlope < 0)
			{
				State = "Found";
			}

			FollowLine();
		}

		if(State == "Found")
		{
			if (Encoder - InitialEncoder < (-2 * 1440))
			{
				State = "Moving Short";
			}
			else
			{
				State = "Moving Long";
			}
		}

		if(State == "Moving Short")
		{
			writeDebugStreamLine("Short");
			Move(20, 20);
			sleep(200);
			Move(0, 0);
			sleep(5000);
			State = "Moving Past Line";
		}

		if(State == "Moving Long")
		{
			writeDebugStreamLine("Long");

			Move(20, 20);

			sleep(450);

			Move(0, 0);

			sleep(5000);

			State = "Moving Past Line";
		}

		if(State == "Moving Past Line")
		{
			if(Encoder - InitialEncoder < (-4 * 1440))
			{
				State = "Ramp";
			}

			FollowLine();
		}

		if(State == "Ramp")
		{
			Move(15, 60);
			sleep(2100);
			Move(80, 80);
			sleep(1300);
			Move(0, 0);
			while(true)
			{
			}
		}
	}
}
