#pragma config(Sensor, S2, IR, sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../../libraries/Motors.h"
#include "HitecnicInfaredLibrary.h"

//eraseDisplay();
//nxtDisplayString(1, "A: %i", A);
//nxtDisplayString(2, "B: %i", B);
//nxtDisplayString(3, "C: %i", C);
//nxtDisplayString(4, "D: %i", D);
//nxtDisplayString(5, "E: %i", E);
int A, B, C, D, E = 0;

void ReadSensorValues()
{
	HTIRS2readAllACStrength(IR, A, B, C, D, E);
}

void ForwardWhileUnderValue(int Limit)
{
	while(A < Limit && B < Limit && C < Limit && D < Limit && E < Limit)
	{
		nxtDisplayString(1, "Forward");
		ReadSensorValues();
	}
}

bool CGreatest()
{
	int Multiplier = 5;
	return (C > A * Multiplier && C > B * Multiplier && C > D * Multiplier && C > E * Multiplier);
}

//returns true if it should turn to the right
bool Side()
{
	if((A + B) > (D + E))
	{
		return false;
	}
	else
	{
		return true;
	}
}

void TurnIntoC()
{
	while(!CGreatest())
	{
		ReadSensorValues();

		if(!Side())
		{
			nxtDisplayString(1, "Left");
		}
		else if(Side())
		{
			nxtDisplayString(1, "Right");
		}
	}
}

task main()
{
	ForwardWhileUnderValue(20);
	TurnIntoC();
	ForwardWhileUnderValue(35);
	TurnIntoC();
	ForwardWhileUnderValue(50);
	TurnIntoC();

	nxtDisplayString(1, "Stop");
	while(true)
	{
	}
}
