#pragma config(Sensor, S1,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../libraries/Bluetooth.c"
#include "../libraries/Motors.h"

task main()
{
	while(true)
	{
		int FirstMessage = 0;
		int SecondMessage = 0;
		int ThirdMessage = 0;

		if(Bluetooth_ReadMessage(&FirstMessage, &SecondMessage, &ThirdMessage))
		{
			Motors_SetSpeed(S1, 1, 1, 0);
			Motors_SetSpeed(S1, 1, 2, 0);

			sleep(10);

			Motors_SetSpeed(S1, 1, 1, FirstMessage);
			Motors_SetSpeed(S1, 1, 2, -SecondMessage);

			nxtDisplayString(1, "MotorA: %i", FirstMessage);
			nxtDisplayString(2, "MotorB: %i", SecondMessage);
			nxtDisplayString(3, "MotorC: %i", ThirdMessage);
		}
	}
}
