#pragma config(Sensor, S1,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../libraries/motors.h"

bool TestJoint(tSensors Port, int DaisyChain, int MotorNumber, int Power)
{
	int InitialEncoder = I2C_GetEncoderPosition(Port, DaisyChain, MotorNumber);
	Motors_SetSpeed(Port, DaisyChain, MotorNumber, Power);
	sleep(1000);
	Motors_SetSpeed(Port, DaisyChain, MotorNumber, 0);
	int FinalEncoder = I2C_GetEncoderPosition(Port, DaisyChain, MotorNumber);
	writeDebugStreamLine("%i", abs(InitialEncoder - FinalEncoder));

	if(abs(InitialEncoder - FinalEncoder) > 400)
	{
		return true;
	}
	return false;
}

task main()
{
	// && TestJoint(S1, 2, 2, 10) && TestJoint(S1, 1, 1, -10) && TestJoint(S1, 1, 2, 10)
	bool RightSide = TestJoint(S1, 2, 1, 20);
	bool LeftSide = TestJoint(S1, 2, 2, 20);
	bool Arm = TestJoint(S1, 1, 1, -100);
	bool Flag = TestJoint(S1, 1, 2, 20);

	eraseDisplay();
	nxtDisplayString(1, "Left Side: %i", LeftSide);
	nxtDisplayString(2, "Right Side: %i", RightSide);
	nxtDisplayString(3, "Arm: %i", Arm);
	nxtDisplayString(4, "Flag: %i", Flag);

	//if there is a failure in any of the parts, beep.
	if(!LeftSide || !RightSide || !Arm || !Flag)
	{
		PlayImmediateTone(100, 100);
	}

	while(nNxtButtonPressed == -1)
	{
	}
}
