#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     IR,             sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     left_front,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left_back,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     right_front,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     right_back,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	to get the old version of this file, before the #include thing, run the following command (without the $ prompt, and ignoring the detached HEAD warning):

	$ git checkout 60dbbb6d04b5b3d36b754dde3bb7f25ded296a46

	then copy anything that you need. (don't change anything, because then you'll have to deal with conflicts.)
	to revert to the way the working tree was before (meaning the latest version), run:

	$ git checkout master
*/

// program parameters
const bool turnAtIrBeacon = false;

#include "autoLOBFEngine.h"
