#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     IR,             sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     left_front,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left_back,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     right_front,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     right_back,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// program parameters
const bool turnAtIrBeacon = false;

#include "autoLOBFEngine.h"
