#pragma config(Sensor, S1,     IR,             sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "HitecnicInfaredLibrary.h"

// algorithm parameters
// threshold for the drop in IR sensor 2 (if it drops to below this, we've reached the cliff)
const int cliff_drop_threshold = 2;
// some number out of 10. if we detect that there are this number or more instances where the
// 	IR signal strengh is going down, then we assume that we're actually going down and we go back
// 	to find the top of the curve.
const int going_down_threshold = 7;
// maximum difference allowed from the previous top of the bell curve
const int curve_top_change_threshold = 1;

int acS1, acS2, acS3, acS4, acS5 = 0;

task main()
{

	int highest_seen_value = 0;

	// TODO go forward here
	// wait for the cliff in IR readings, then break
	while(acS1 < cliff_drop_threshold)
	{
		HTIRS2readAllACStrength(IR, acS1, acS2, acS3, acS4, acS5);
	}

	nxtDisplayString(3, "hit cliff");

	// start trying to find the spike
	bool going_down = false;
	while(!going_down)
	{
		HTIRS2readAllACStrength(IR, acS1, acS2, acS3, acS4, acS5);
		int previous_ir_value[10];
		int previous_ir_value_difference[9];

		// set the new highest seen value
		if (highest_seen_value < acS3) highest_seen_value = acS3;

		for (int i = 0; i < 10; i++)
		{
			int number_of_negative_ir_differences = 0;

			// add the new data
			if (i < 10)
			{
				// we're in the middle (or start) of the stack, shift lower
				previous_ir_value[i] = previous_ir_value[i+1];
			} else
			{
				// i == 10, so we're at the top of the stack
				// populate with the new data
				previous_ir_value[i] = acS3;
			}

			// if this is negative, then we're probably going down
			previous_ir_value_difference[i] = previous_ir_value[i+1] - previous_ir_value[i];
			if (previous_ir_value_difference[i] < 0)
			{
				number_of_negative_ir_differences++;
			}
			// determine if we're going down with a threshold of 7/9 or more
			if (number_of_negative_ir_differences >= going_down_threshold) going_down = true;
		}
	}

	// now the trend is definitely going down, let's back up and find the highest value
	// TODO this will stop slightly before the top
	nxtDisplayString(1, "pull me backwards");
	// TODO go back here
	bool reached_highest_value = false;
	while(!reached_highest_value)
	{
		HTIRS2readAllACStrength(IR, acS1, acS2, acS3, acS4, acS5);
		if (highest_seen_value + curve_top_change_threshold > acS3 &&
		    acS3 < highest_seen_value - curve_top_change_threshold)
		{
			reached_highest_value = true;
		}
	}
}
