#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S1_C1_1,    TopJoint,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    BottomJoint,          tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    Turret,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void sweepServo(int startPosition, int endPosition, TServoIndex ServoName, int TimeToSweep)
{
	float delayTime;
	delayTime = TimeToSweep/abs(endPosition - startPosition);
	int currentPosition = startPosition;
	if(endPosition>startPosition)
	{
		while(currentPosition < endPosition)
		{
			servo[ServoName] = currentPosition;
			currentPosition += 1;
			wait1Msec(delayTime);
		}
	}
	else
	{
		while(endPosition < currentPosition)
		{
			servo[ServoName] = currentPosition;
			currentPosition -= 1;
			wait1Msec(delayTime);
		}
	}
}

task main()
{
	servo[BottomJoint] = 80;
	servo[Turret] = 10;
	servo[TopJoint] = 150;
	sweepServo(20, 150, BottomJoint, 10000);
	sweepServo(100, 255, TopJoint, 5000);  //range for the TopJoint...  100 is the highest position, 255 is the lowest
	sweepServo(10, 245, Turret, 10000);  // range for the Turret...
	sweepServo(245, 10, Turret, 10000);  // range for the Turret...
	wait1Msec(10000);
}
