#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CCustom)
#pragma config(Sensor, S3,     ,               sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../libraries/I2C.h"
#include "JoystickDriver.c"

// program parameters
const int deadband = 8;
const int baseJoyModifier = 1.5;

float userJoyModifier = 1;
int rightpower, leftpower = 0;

task main()
{
	// TODO: normalize the arm position to the bottom here

//	const int baseArmEncoderCount = I2C_GetEncoderPosition(S1, 1, 1);

	while(true)
	{
		rightpower = joystick.joy1_y2 / baseJoyModifier * userJoyModifier;
		leftpower = joystick.joy1_y1 / baseJoyModifier * userJoyModifier;

		// deadband
		if (abs(rightpower) < deadband)
		{
			rightpower = 0;
		}
		if (abs(leftpower) < deadband)
		{
			leftpower = 0;
		}

		servo[servo1] = 0;
		Sleep(10);
	}
}
