#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void MoveDirection(string i)
{
	if(i == "Stop")
	{
		motor[motorD] = 0;
		motor[motorE] = 0;
		motor[motorF] = 0;
	}
	if (i == "Forward")
	{
		motor[motorD] = 10;
		motor[motorE] = 0;
		motor[motorF] = -10;
	}

	if (i == "Backward")
	{
		motor[motorD] = -10;
		motor[motorE] = 0;
		motor[motorF] = 10;
	}

	if (i == "LeftBackward")
	{
		motor[motorD] = 0;
		motor[motorE] = -10;
		motor[motorF] = 10;
	}

	if (i == "RightForward")
	{
		motor[motorD] = 0;
		motor[motorE] = 10;
		motor[motorF] = -10;
	}

	if (i == "RightBackward")
	{
		motor[motorE] = 10;
		motor[motorD] = -10;
		motor[motorF] = 0;
	}

	if (i == "LeftForward")
	{
		motor[motorE] = -10;
		motor[motorD] = 10;
		motor[motorF] = 0;
	}
}

task main()
{
	string One = "LeftForward";
	string Two = "RightForward";
	string Three = "Stop";

	MoveDirection(One);
	sleep(2000);
	MoveDirection(Two);
	sleep(2000);
	MoveDirection(Three);
	while(true)
	{
	}
}
