#pragma config(Sensor, S1,     ,               sensorI2CCustom)
#pragma config(Sensor, S2,     ,               sensorI2CCustom)
#pragma config(Sensor, S3,     ,               sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../Auto/libraries/I2C.h"
#include "JoystickDriver.c"

/*

	IMPORTANT: DESIGNED FOR VARSITY'S JARVIS CHASSIS.

*/

int rightpower, leftpower = 0;
int rightpowerGlobal, leftpowerGlobal = 0;

task main()
{
	while(true)
	{
		rightpower = joystick.joy1_y2 / 2;
		leftpower = joystick.joy1_y1 / 2;
		I2C_SetMotorSpeed(S1, 2, 1, rightpower);
		I2C_SetMotorSpeed(S1, 2, 2, -leftpower);
	}
}
