#pragma config(Sensor, S1,     ,               sensorI2CCustom)
#pragma config(Sensor, S2,     ,               sensorI2CCustom)
#pragma config(Sensor, S3,     ,               sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../libraries/I2C.h"
#include "JoystickDriver.c"

/*

	IMPORTANT: DESIGNED FOR VARSITY'S JARVIS CHASSIS.

*/

int rightpower, leftpower = 0;
int rightpowerGlobal, leftpowerGlobal = 0;

task main()
{
	while(true)
	{
		rightpower = joystick.joy1_y2;		//read joystick y values (both sticks)
		leftpower = joystick.joy1_y1;

		if(abs(rightpower) < 8)			//deadband with threshold of 8
		{
			rightpower = 0;
		}

		if(abs(leftpower) < 8)			//deadband with threshold of 8

		{
			leftpower = 0;
		}

		rightpowerGlobal = rightpower;
		leftpowerGlobal = -leftpower;

		/*
			Motor 1 Daisychain 1 on S1 is left front
			Motor 2 Daisychain 1 on S1 is left back
			Motor 1 Daisychain 2 on S1 is right front
			Motor 2 Daisychain 2 on S1 is right back
		*/

		I2C_SetMotorSpeed(S1, 2, 1, rightpower);
		I2C_SetMotorSpeed(S1, 2, 2, -leftpower);
		Sleep(10);
	}
}
