#pragma config(Sensor, S1,     ,               sensorI2CCustom)
#pragma config(Sensor, S2,     ,               sensorI2CCustom)
#pragma config(Sensor, S3,     ,               sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../libraries/I2C.h"
#include "../libraries/Arm.h"
#include "JoystickDriver.c"

/*

	IMPORTANT: DESIGNED FOR VARSITY'S JARVIS CHASSIS.

	TODO: add support for speed modifiers.

*/

// program parameters
const int deadband = 8;
const int baseJoyModifier = 1.5;
const int baseArmModifier = 1.5;

float userJoyModifier = 1;
float userArmModifier = 1; // this doesn't do anything meaningful yet
int rightpower, leftpower, armpower = 0;

task main()
{
	while(true)
	{
		// switch the drive multiplier mode
		if (joy1Btn(4) == 1) {
			if (userJoyModifier == 1) userJoyModifier = 0.5;
			if (userJoyModifier == 0.5) userJoyModifier = 1;
		}

		rightpower = joystick.joy1_y2 / baseJoyModifier * userJoyModifier;
		leftpower = joystick.joy1_y1 / baseJoyModifier * userJoyModifier;
		armpower = joystick.joy2_y1 / baseArmModifier * userArmModifier;

		// deadband
		if (abs(rightpower) < deadband)
		{
			rightpower = 0;
		}
		if (abs(leftpower) < deadband)
		{
			leftpower = 0;
		}
		if (abs(armpower) < deadband)
		{
			armpower = 0;
		}

		I2C_SetMotorSpeed(S1, 2, 1, rightpower);
		I2C_SetMotorSpeed(S1, 2, 2, -leftpower);

		Arm_SetSpeed(armpower);
		Arm_Update();

		Sleep(10);
	}
}
