#pragma config(Sensor, S1,     ,               sensorI2CCustom)
#pragma config(Sensor, S2,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../libraries/motors.h"
#include "../libraries/servos.h"
#include "JoystickDriver.c"

int ServoPosition = 0;
task main()
{
	Motors_SetSpeed(S1, 1, 1, -(10));
	Motors_SetSpeed(S1, 1, 2, (10));

	sleep(1000);


	while(true)
	{
			getJoystickSettings(joystick);



			Motors_SetSpeed(S1, 1, 1, -(joystick.joy1_y1 / 1.28 + joystick.joy1_x1 / 4));
			Motors_SetSpeed(S1, 1, 2, (joystick.joy1_y1 / 1.28 - joystick.joy1_x1 / 4));


			if(joy1Btn(6) == 1)
			{
				writeDebugStreamLine("Working");
				Motors_SetSpeed(S1, 2, 2, 30);
			}
			else if(joy1Btn(5) == 1)
			{
				Motors_SetSpeed(S1, 2, 2, -30);
			}
			else
			{
				Motors_SetSpeed(S1, 2, 2, 0);
			}

			if(joy1Btn(2) == 1)
			{
				Servos_SetPosition(S1, 3, 1, 0);
			}
			else if(joy1Btn(3) == 1)
			{
				Servos_SetPosition(S1, 3, 1, 50);
			}


			sleep(10);
		}
}
